SELECT name,
       setting            AS value,
       unit,
       context,
       category,
       short_desc         AS description
FROM pg_settings
WHERE name IN (
    'max_connections',
    'shared_buffers',
    'effective_cache_size',
    'work_mem',
    'maintenance_work_mem',
    'temp_buffers',
    'wal_buffers',
    'max_wal_size',
    'min_wal_size',
    'checkpoint_timeout',
    'checkpoint_completion_target',
    'synchronous_commit',
    'synchronous_standby_names',
    'wal_level',
    'max_wal_senders',
    'archive_mode',
    'archive_command',
    'wal_keep_size',
    'max_worker_processes',
    'max_parallel_workers',
    'max_parallel_workers_per_gather',
    'autovacuum',
    'autovacuum_max_workers',
    'autovacuum_naptime',
    'autovacuum_vacuum_threshold',
    'autovacuum_vacuum_scale_factor',
    'autovacuum_vacuum_cost_limit',
    'autovacuum_vacuum_cost_delay',
    'autovacuum_freeze_max_age',
    'vacuum_cost_limit',
    'effective_io_concurrency',
    'random_page_cost',
    'fsync',
    'full_page_writes',
    'idle_in_transaction_session_timeout',
    'statement_timeout',
    'lock_timeout',
    'default_statistics_target',
    'track_activities'
)
ORDER BY name
LIMIT 100;
